"""Add adapter stats fields

Revision ID: 5227f3e24895
Revises: 007ebf675ee5
Create Date: 2026-06-04 18:58:55.681358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5227f3e24895'
down_revision: Union[str, Sequence[str], None] = '007ebf675ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('adapters', sa.Column('bands', sa.JSON(), nullable=False))
    op.add_column('adapters', sa.Column('channel', sa.Integer(), nullable=True))
    op.add_column('adapters', sa.Column('rssi', sa.Integer(), nullable=True))
    op.add_column('adapters', sa.Column('rx', sa.Integer(), nullable=True))
    op.add_column('adapters', sa.Column('tx', sa.Integer(), nullable=True))
    op.add_column('adapters', sa.Column('status', sa.String(), nullable=True))
    op.add_column('adapters', sa.Column('capabilities', sa.JSON(), nullable=False))
    op.add_column('ap_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ap_sessions', 'projects', ['project_id'], ['id'])
    op.add_column('attack_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attack_sessions', 'projects', ['project_id'], ['id'])
    op.add_column('captures', sa.Column('status', sa.String(), nullable=False))
    op.add_column('captures', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'captures', 'projects', ['project_id'], ['id'])
    op.add_column('clients', sa.Column('packets', sa.Integer(), nullable=True))
    op.add_column('crack_jobs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crack_jobs', 'projects', ['project_id'], ['id'])
    op.add_column('credentials', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('credentials', sa.Column('bssid', sa.String(), nullable=True))
    op.add_column('credentials', sa.Column('username', sa.String(), nullable=True))
    op.add_column('credentials', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('credentials', 'ap_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'credentials', 'projects', ['project_id'], ['id'])
    op.add_column('job_queue', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_queue', 'projects', ['project_id'], ['id'])
    op.add_column('networks', sa.Column('cipher', sa.String(), nullable=True))
    op.add_column('networks', sa.Column('auth', sa.String(), nullable=True))
    op.add_column('networks', sa.Column('beacons', sa.Integer(), nullable=True))
    op.add_column('networks', sa.Column('data', sa.Integer(), nullable=True))
    op.add_column('networks', sa.Column('wps', sa.Boolean(), nullable=True))
    op.add_column('scopes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scopes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'project_id')
    op.drop_constraint(None, 'scopes', type_='foreignkey')
    op.drop_column('scopes', 'project_id')
    op.drop_column('networks', 'wps')
    op.drop_column('networks', 'data')
    op.drop_column('networks', 'beacons')
    op.drop_column('networks', 'auth')
    op.drop_column('networks', 'cipher')
    op.drop_constraint(None, 'job_queue', type_='foreignkey')
    op.drop_column('job_queue', 'project_id')
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.alter_column('credentials', 'ap_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('credentials', 'type')
    op.drop_column('credentials', 'username')
    op.drop_column('credentials', 'bssid')
    op.drop_column('credentials', 'project_id')
    op.drop_constraint(None, 'crack_jobs', type_='foreignkey')
    op.drop_column('crack_jobs', 'project_id')
    op.drop_column('clients', 'packets')
    op.drop_constraint(None, 'captures', type_='foreignkey')
    op.drop_column('captures', 'project_id')
    op.drop_column('captures', 'status')
    op.drop_constraint(None, 'attack_sessions', type_='foreignkey')
    op.drop_column('attack_sessions', 'project_id')
    op.drop_constraint(None, 'ap_sessions', type_='foreignkey')
    op.drop_column('ap_sessions', 'project_id')
    op.drop_column('adapters', 'capabilities')
    op.drop_column('adapters', 'status')
    op.drop_column('adapters', 'tx')
    op.drop_column('adapters', 'rx')
    op.drop_column('adapters', 'rssi')
    op.drop_column('adapters', 'channel')
    op.drop_column('adapters', 'bands')
    op.drop_table('projects')
    # ### end Alembic commands ###
